name: Trigger Vercel deploy (prod)

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  trigger-vercel-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger suite.turbot.com deployment
        uses: peter-evans/repository-dispatch@bf47d102fdb849e755b0b0023ea3e81a44b6f570 # v2
        with:
          token: ${{ secrets.GH_PAT }}
          repository: turbot/suite.turbot.com
          event-type: deploy-docs-production
          client-payload: '{"docs_update": "pipes"}'
